
import javax.swing.JMenuItem;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author nmtun
 */
public class Display extends javax.swing.JFrame {

    /**
     * Creates new form display
     */
    public Display() {
        initComponents();
    }

    public JTextArea getTxtDisplay() {
        return txtDisplay;
    }

    public void setTxtDisplay(JTextArea txtDisplay) {
        this.txtDisplay = txtDisplay;
    }

    public JMenuItem getMenu_edit_changefont() {
        return jMenuItem14;
    }

    public void setMenu_edit_changefont(JMenuItem menu_edit_changefont) {
        this.jMenuItem14 = menu_edit_changefont;
    }

    public JMenuItem getMenu_edit_copy() {
        return menu_edit_copy;
    }

    public void setMenu_edit_copy(JMenuItem menu_edit_copy) {
        this.menu_edit_copy = menu_edit_copy;
    }

    public JMenuItem getMenu_edit_cut() {
        return menu_edit_cut;
    }

    public void setMenu_edit_cut(JMenuItem menu_edit_cut) {
        this.menu_edit_cut = menu_edit_cut;
    }

    public JMenuItem getMenu_edit_find() {
        return menu_edit_find;
    }

    public void setMenu_edit_find(JMenuItem menu_edit_find) {
        this.menu_edit_find = menu_edit_find;
    }

    public JMenuItem getMenu_edit_paste() {
        return menu_edit_paste;
    }

    public void setMenu_edit_paste(JMenuItem menu_edit_paste) {
        this.menu_edit_paste = menu_edit_paste;
    }

    public JMenuItem getMenu_edit_redo() {
        return menu_edit_redo;
    }

    public void setMenu_edit_redo(JMenuItem menu_edit_redo) {
        this.menu_edit_redo = menu_edit_redo;
    }

    public JMenuItem getMenu_edit_replace() {
        return jMenuItem13;
    }

    public void setMenu_edit_replace(JMenuItem menu_edit_replace) {
        this.jMenuItem13 = menu_edit_replace;
    }

    public JMenuItem getMenu_edit_selectall() {
        return menu_edit_selectall;
    }

    public void setMenu_edit_selectall(JMenuItem menu_edit_selectall) {
        this.menu_edit_selectall = menu_edit_selectall;
    }

    public JMenuItem getMenu_edit_undo() {
        return menu_edit_undo;
    }

    public void setMenu_edit_undo(JMenuItem menu_edit_undo) {
        this.menu_edit_undo = menu_edit_undo;
    }

    public JMenuItem getMenu_file_exit() {
        return menu_file_exit;
    }

    public void setMenu_file_exit(JMenuItem menu_file_exit) {
        this.menu_file_exit = menu_file_exit;
    }

    public JMenuItem getMenu_file_new() {
        return menu_file_new;
    }

    public void setMenu_file_new(JMenuItem menu_file_new) {
        this.menu_file_new = menu_file_new;
    }

    public JMenuItem getMenu_file_open() {
        return menu_file_open;
    }

    public void setMenu_file_open(JMenuItem menu_file_open) {
        this.menu_file_open = menu_file_open;
    }

    public JMenuItem getMenu_file_save() {
        return menu_file_save;
    }

    public void setMenu_file_save(JMenuItem menu_file_save) {
        this.menu_file_save = menu_file_save;
    }

    public JMenuItem getMenu_file_saveas() {
        return menu_file_saveas;
    }

    public void setMenu_file_saveas(JMenuItem menu_file_saveas) {
        this.menu_file_saveas = menu_file_saveas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtDisplay = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_file_new = new javax.swing.JMenuItem();
        menu_file_open = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menu_file_save = new javax.swing.JMenuItem();
        menu_file_saveas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menu_file_exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menu_edit_selectall = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menu_edit_cut = new javax.swing.JMenuItem();
        menu_edit_copy = new javax.swing.JMenuItem();
        menu_edit_paste = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menu_edit_undo = new javax.swing.JMenuItem();
        menu_edit_redo = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menu_edit_find = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtDisplay.setColumns(20);
        txtDisplay.setRows(5);
        jScrollPane1.setViewportView(txtDisplay);

        jMenu1.setText("File");

        menu_file_new.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menu_file_new.setText("New");
        jMenu1.add(menu_file_new);

        menu_file_open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menu_file_open.setText("Open");
        jMenu1.add(menu_file_open);
        jMenu1.add(jSeparator1);

        menu_file_save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menu_file_save.setText("Save");
        jMenu1.add(menu_file_save);

        menu_file_saveas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_file_saveas.setText("Save as");
        jMenu1.add(menu_file_saveas);
        jMenu1.add(jSeparator2);

        menu_file_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menu_file_exit.setText("Exit");
        jMenu1.add(menu_file_exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        menu_edit_selectall.setText("Select all");
        jMenu2.add(menu_edit_selectall);
        jMenu2.add(jSeparator3);

        menu_edit_cut.setText("Cut");
        jMenu2.add(menu_edit_cut);

        menu_edit_copy.setText("Copy");
        jMenu2.add(menu_edit_copy);

        menu_edit_paste.setText("Paste");
        jMenu2.add(menu_edit_paste);
        jMenu2.add(jSeparator4);

        menu_edit_undo.setText("Undo");
        jMenu2.add(menu_edit_undo);

        menu_edit_redo.setText("Redo");
        jMenu2.add(menu_edit_redo);
        jMenu2.add(jSeparator5);

        menu_edit_find.setText("Find");
        jMenu2.add(menu_edit_find);

        jMenuItem13.setText("Replace");
        jMenu2.add(jMenuItem13);
        jMenu2.add(jSeparator6);

        jMenuItem14.setText("Change font");
        jMenu2.add(jMenuItem14);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and Display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenuItem menu_edit_copy;
    private javax.swing.JMenuItem menu_edit_cut;
    private javax.swing.JMenuItem menu_edit_find;
    private javax.swing.JMenuItem menu_edit_paste;
    private javax.swing.JMenuItem menu_edit_redo;
    private javax.swing.JMenuItem menu_edit_selectall;
    private javax.swing.JMenuItem menu_edit_undo;
    private javax.swing.JMenuItem menu_file_exit;
    private javax.swing.JMenuItem menu_file_new;
    private javax.swing.JMenuItem menu_file_open;
    private javax.swing.JMenuItem menu_file_save;
    private javax.swing.JMenuItem menu_file_saveas;
    private javax.swing.JTextArea txtDisplay;
    // End of variables declaration//GEN-END:variables
}
